name: GitHub Actions Multiple job demo
run-name: GitHub Actions Multiple job demo
on: [push]
jobs:
  job-01:
    runs-on: ubuntu-latest
    steps:
       - name: Check out repository code
         uses: actions/checkout@v4
       - name: list content in the workspace
         run: ls -al  ${{ github.workspace }}
  job-02: 
     needs: job-01
     runs-on: ubuntu-latest
     steps:
        - name: list content in the workspace
          run: ls -al  ${{ github.workspace }}
