name: GitHub Actions Multiple job demo
run-name: GitHub Actions Multiple job demo
on: [push]
jobs:
  job-01:
    runs-on: ubuntu-latest
    steps:
      - name: create a temp file
        run: echo hello > ${{ github.workspace }}/hello.txt
  job-02: 
     needs: job-01
     runs-on: ubuntu-latest
     steps:
       - name: read  temp file
         run: cat ${{ github.workspace }}/hello.txt
